apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: employee-app
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-user: appuser
  mysql-password: apppassword
  mysql-database: employeedb
